# Site
name: 'Glow With Rho'
description: 'Inspiring better beauty choices through skincare science.'
logo: 'assets/images/logo.jpg'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'rhocosmetics'
email: 'noreply@rhocosmetics.com'
mailchimp-list: 'https://rhocosmetics.us20.list-manage.com/subscribe?u=8f91c1ac316d14a2cef964d63&id=752dd73b7d'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    rachel:
      name:           Rachel
      site:           https://rhocosmetics.com
      avatar:         assets/images/meet-our-founder.jpg
      bio:            "Hi. I'm Rachel, the founder and formulation chemist behind Rho Cosmetics. Better beauty choices begins with a true understanding of what we put on our skin. Let's talk skincare!"
      email:          rachel@rhocosmetics.com
      instagram:        https://instagram.com/rhocosmetics

 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: rachel
      avatar: /assets/images/meet-our-founder.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]